name: '\U0001F680 New feature proposal'
description: Propose a new feature to be added to Aira
labels: [':rocket: enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature request!
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: 'Clear and concise description of the problem. Please make the reason and use cases as detailed as possible. If you intend to submit a PR for this issue, let us know in the description. Thanks!'
      placeholder: As a user of Aira, I want [goal / wish] so that [benefit].
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: 'Describe the suggested implementation for this feature.'
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternative
      description: Clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/lunof/aira/blob/main/CODE_OF_CONDUCT.md)
          required: true
        # TODO: Uncomment the following lines after creating the CONTRIBUTING.md file
        # - label: Read the [Contributing Guidelines](https://github.com/lunof/aira/blob/main/CONTRIBUTING.md).
        #   required: true
        - label: Check that there isn't already an issue requesting the same feature to avoid creating a duplicate.
          required: true
